name: Create PR for new Release-note with template

on:
  push:
    branches:
      - master
    paths:
      - '_data/latest/**'

jobs:
  add-release-note:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.WEBSITE_TOKEN}}

    steps:    
    - name: Install jq for json manipulation
      run: sudo apt-get install jq

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create new release note
      run: |
        VERSION="`jq -r '.version' _data/latest/metadata.json`"
        mkdir downloads/release-notes/$VERSION
        cp downloads/RELEASE_NOTE.md downloads/release-notes/$VERSION

    - name: Push changes for the new release note
      run: |
        git checkout automate-release-folder-$GITHUB_SHA 2>/dev/null || git checkout -b automate-release-folder-$GITHUB_SHA
        git pull origin master
        
        git config --global user.email "ballerina-bot@ballerina.org"
        git config --global user.name "ballerina-bot"
        
        VERSION="`jq -r '.version' _data/latest/metadata.json`"
        git add downloads/release-notes/$VERSION
        git commit --allow-empty -m 'Add releaste note template for the new release'
        
        git push --set-upstream origin automate-release-folder-$GITHUB_SHA
        echo 'Successfully pushed to automate-release-folder-$GITHUB_SHA branch'

    - name: Create pull request for the new release note
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -m '[Automated] Add release note template for the new release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
